import {DEFAULT_SETTINGS} from './legacyV60/config/defaults';
import type {Plan,Cylinder,Segment} from '../../core/types';
import {numberValue} from '../../core/validation';
// 架空デモ専用。実在する供給元の換算表ではない。
export const demoProduct={id:'DEMO-C2',name:'架空DEMO-C2（内容積2 L／公称容量未登録）',volume:2,reserve:0.5,atmosphere:0.1,maxPressure:15};
export function usable(c:Cylinder):number|null{const p=numberValue(c.pressure,0,demoProduct.maxPressure);return c.product===demoProduct.id&&c.pressureUnit==='MPa'&&p!==null?demoProduct.volume*Math.max(p-demoProduct.reserve,0)/demoProduct.atmosphere:null;}
export const newSegment=(i:number):Segment=>({id:`s${i}`,name:`区間${i}`,times:{move:'',exam:'',wait:'',connect:'',delay:''},oxygen:'',air:'',power:'unknown',oxygenRate:'',airRate:'',sourceConfirmed:false});
export const newCylinder=(i:number):Cylinder=>({id:`DEMO-${i}`,resource:'oxygen',product:demoProduct.id,pressure:'',pressureUnit:'MPa',role:'connected',compatible:false,exchangePoint:'',exchangeResponsible:false,exchangeProcedure:false});
export function initialV60Settings(){return {legacyEnabled:'yes',legacyCapacity:String(DEFAULT_SETTINGS.cylinderCapacity),legacyFull:String(DEFAULT_SETTINGS.fullPressure),legacyReserve:String(DEFAULT_SETTINGS.reservePressure),legacyCompensation:String(DEFAULT_SETTINGS.circuitCompensationFlow),legacyFactor:String(DEFAULT_SETTINGS.safetyFactor*100)};}
export function emptyPlan(mode:Plan['mode']):Plan{return {mode,environment:'internal',profileId:mode==='demo'?'fictional-demo':'v60',configurationId:mode==='demo'?'DEMO-01':'',matched:false,fields:mode==='clinical'?initialV60Settings():{},cylinders:[],segments:[mode==='clinical'?{...newSegment(1),times:{move:'',exam:'0',wait:'0',connect:'0',delay:'0'}}:newSegment(1)],powerMinutes:'',powerConfirmed:false,external:{vehicle:false,fixation:false,gas:false,power:false,destination:false},readings:{}};}
export function demoExample():Plan{const p=emptyPlan('demo');p.matched=true;p.powerMinutes='60';p.powerConfirmed=true;p.cylinders=[{...newCylinder(1),id:'O2-DEMO-A',pressure:'10',compatible:true},{...newCylinder(2),id:'AIR-DEMO-A',resource:'air',pressure:'10',compatible:true}];p.segments=[{...newSegment(1),name:'病室 → 検査室',times:{move:'10',exam:'5',wait:'2',connect:'1',delay:'2'},oxygen:'O2-DEMO-A',air:'AIR-DEMO-A',power:'battery',oxygenRate:'5',airRate:'3',sourceConfirmed:true},{...newSegment(2),name:'検査室 → 病室',times:{move:'10',exam:'0',wait:'0',connect:'0',delay:'0'},oxygen:'O2-DEMO-A',air:'AIR-DEMO-A',power:'battery',oxygenRate:'5',airRate:'3',sourceConfirmed:true}];return p;}
