import {useId} from 'react';
import type {Plan} from '../core/types';
import {numberValue,displayTime,displayAmount,displayAvailable} from '../core/validation';
import {calculateOxygen} from '../modules/transport/legacyV60/utils/oxygenCalculation';
const settings=[['legacyCapacity','ボンベ容量','L'],['legacyFull','満充填圧','MPa'],['legacyReserve','安全残圧','MPa'],['legacyCompensation','回路補正流量','L/min'],['legacyFactor','安全係数','%']] as const;
export function LegacyV60Inputs({plan,change}:{plan:Plan;change:(p:Plan)=>void}){const id=useId();return <section className="reference-input"><h3>ボンベ・計算設定</h3><p>添付式は実機の消費量を確認した式ではありません。院内・成人V60の式の動作確認専用です。</p><label className="check"><input type="checkbox" checked={plan.fields.legacyEnabled==='yes'} onChange={e=>change({...plan,fields:{...plan.fields,legacyEnabled:e.target.checked?'yes':''}})}/><span>添付式のシミュレーションを表示する（臨床判断には使用しない）</span></label><><p>現在残圧・FiO₂・MinVent・Total Leak・移動時間は上の入力を使います。下の値は仕様と仮定を確認して入力してください。初期値は添付コードの設定です。院内・メーカー承認値ではありません。実際の仕様と仮定に合わせて変更してください。</p><div className="grid">{settings.map(([key,label,unit])=><div className="field" key={key}><label htmlFor={id+key}>{label}</label><div className="input-unit"><input id={id+key} inputMode="decimal" value={plan.fields[key]??''} onChange={e=>change({...plan,fields:{...plan.fields,[key]:e.target.value}})}/><span>{unit}</span></div><small>{key==='legacyCapacity'?'満充填時に入っている酸素量（例：500 L級）。容器そのものの内容積ではありません。':key==='legacyFactor'?'添付仕様の50〜100%。この係数で安全性が保証されるわけではありません。':'仕様または利用者が置いた仮定。推奨値ではありません。'}</small></div>)}</div><button onClick={()=>change({...plan,segments:plan.segments.map(s=>({...s,times:{...s.times,exam:'0',wait:'0',connect:'0',delay:'0'}}))})}>検査・待機・接続・追加遅延はない（0分を入力）</button></></section>;}
export function LegacyV60Results({plan}:{plan:Plan}){
 const raw=[plan.fields.cylinderPressure,plan.fields.fio2,plan.fields.vent,plan.fields.leak,...settings.map(([key])=>plan.fields[key]),...plan.segments.flatMap(s=>Object.values(s.times))];
 const nums=raw.map(x=>numberValue(x??''));let error='';let r:ReturnType<typeof calculateOxygen>|null=null;
 if(nums.some(x=>x===null))error='現在残圧・FiO₂・MinVent・Total Leak・5つの計算設定・全時間を入力してください。不要な時間も0を入力します。';
 else {try{const [pressure,fio,vent,leak,capacity,full,reserve,comp,factor,...times]=nums as number[];r=calculateOxygen({currentPressure:pressure,fio2Percent:fio,minuteVentilation:vent,leakFlow:leak,transportMinutes:times.reduce((a,b)=>a+b,0)},{cylinderCapacity:capacity,fullPressure:full,reservePressure:reserve,circuitCompensationFlow:comp,safetyFactor:factor/100});}catch(e){error=e instanceof Error?e.message:'計算停止';}}
 return <section aria-label="添付V60式のシミュレーション" className="reference-result"><h3>添付式のシミュレーション · 未検証</h3><p className="notice">実際のV60酸素残時間ではありません。MinVentとTotal Leakを加算する仮定は未確認です。電源・空気は供給を確保する想定です。酸素の式上の時間差だけを示します。</p>{error?<p className="error" role="alert">{error}</p>:r&&<><p>式上の利用可能量 {displayAvailable(r.usableOxygenLiters)} L ／ 式上の酸素消費量 {displayAmount(r.oxygenConsumption)} L/min</p>{r.safeDurationMinutes===null?<p>FiO₂ 21%は添付式の時間評価対象外。無限時間や酸素不要とは表示しません。</p>:<><div className={'overall '+(r.remainingMargin!<0?'danger':'')} role="status"><strong>{r.remainingMargin!<0?`酸素の参考計算では ${displayAmount(-r.remainingMargin!)} 分不足しています`:r.remainingMargin===0?'酸素の参考計算では予定時間と同じです（余裕0分）':`酸素の参考計算では ${displayAvailable(r.remainingMargin)} 分の余裕があります`}</strong><p>未検証の式・入力条件による時間差です。実際の持続時間や搬送可否は保証しません。</p></div><h3>係数適用後の式上の時間：{displayTime(r.safeDurationMinutes)}</h3><p>評価時間 {displayTime(r.input.transportMinutes)} ／ {r.remainingMargin!<0?`式上 ${displayAmount(-r.remainingMargin!)} 分不足`:`式上の時間差 +${displayAvailable(r.remainingMargin)} 分`}</p></>}<details><summary>Total Leakを変えた場合の式の比較</summary>{r.simulation.map(s=><p key={s.increment}>Total Leak +{s.increment} L/min：{displayTime(s.safeDurationMinutes)}</p>)}<p>添付コードの比較条件（+0/+10/+20）。実際のリーク変動予測や推奨値ではありません。</p></details></>}<details><summary>移植式と根拠</summary><p>出典：利用者添付 V60--main.zip、oxygenCalculation.ts。メーカー検証済み資料ではありません。</p><p>ガス量 = ボンベ容量 × max（残圧−安全残圧, 0）÷満充填圧。</p><p>式上の消費量 =（MinVent＋Total Leak＋補正流量）×（FiO₂/100−0.21）÷0.79。係数適用時間 = ガス量÷式上の消費量×安全係数（%÷100）。</p><p>丸め・表示はお助け君の規則を適用：時間/量を切捨て、不足を切上げ。元コードの緑・黄・赤の搬送判定は採用しません。交換・補充は未対応。モデル版 imported-v60-experimental-1.0。</p></details></section>;
}
