import {useId} from 'react';
import type {Plan} from '../core/types';
import {numberValue,displayTime,displayAmount,displayAvailable} from '../core/validation';
import {calculateOxygen} from '../modules/transport/legacyV60/utils/oxygenCalculation';
const settings=[['legacyCapacity','ボンベ容量','L'],['legacyFull','満充填圧','MPa'],['legacyReserve','安全残圧','MPa'],['legacyCompensation','回路補正流量','L/min'],['legacyFactor','安全係数','%']] as const;
export function LegacyV60Inputs({plan,change}:{plan:Plan;change:(p:Plan)=>void}){const id=useId();return <section className="reference-input"><h3>ボンベ・計算設定</h3><p>初期設定：500 L・14.7 MPa・1 MPa・5 L/min・80%。使用する仕様に合わせて変更できます。設定値は実機で未検証です。</p>{plan.profileId!=='v60'&&<p className="notice">共通の仮設定です。この機種の承認仕様ではありません。回路補正流量・安全係数は計算モデル未登録のため残時間計算には使いません。</p>}<div className="grid">{settings.map(([key,label,unit])=><div className="field" key={key}><label htmlFor={id+key}>{label}</label><div className="input-unit"><input id={id+key} inputMode="decimal" value={plan.fields[key]??''} onChange={e=>change({...plan,fields:{...plan.fields,[key]:e.target.value}})}/><span>{unit}</span></div><small>{key==='legacyCapacity'?'満充填時に入っている酸素量（例：500 L級）。容器そのものの内容積ではありません。':key==='legacyFactor'?'添付仕様の50〜100%。この係数で安全性が保証されるわけではありません。':'仕様または利用者が置いた仮定。推奨値ではありません。'}</small></div>)}</div><button onClick={()=>change({...plan,segments:plan.segments.map(s=>({...s,times:{...s.times,exam:'0',wait:'0',connect:'0',delay:'0'}}))})}>検査・待機・接続・追加遅延はない（0分を入力）</button></section>;}
export function LegacyV60Results({plan}:{plan:Plan}){
 const raw=[plan.fields.cylinderPressure,plan.fields.fio2,plan.fields.vent,plan.fields.leak,...settings.map(([key])=>plan.fields[key]),...plan.segments.flatMap(s=>Object.values(s.times))];
 const nums=raw.map(x=>numberValue(x??''));let error='';let r:ReturnType<typeof calculateOxygen>|null=null;
 if(nums.some(x=>x===null))error='現在残圧・FiO₂・MinVent・Total Leak・5つの計算設定・全時間を入力してください。不要な時間も0を入力します。';
 else {try{const [pressure,fio,vent,leak,capacity,full,reserve,comp,factor,...times]=nums as number[];r=calculateOxygen({currentPressure:pressure,fio2Percent:fio,minuteVentilation:vent,leakFlow:leak,transportMinutes:times.reduce((a,b)=>a+b,0)},{cylinderCapacity:capacity,fullPressure:full,reservePressure:reserve,circuitCompensationFlow:comp,safetyFactor:factor/100});}catch(e){error=e instanceof Error?e.message:'計算停止';}}
 return <section aria-label="酸素の参考計算" className="reference-result"><p className="notice">参考計算（式は実機で未検証）。電源・空気の供給を確保する前提です。搬送可否を保証しません。</p>{error?<p className="error" role="alert">{error}</p>:r&&<>{r.safeDurationMinutes===null?<p>FiO₂ 21%は添付式の時間評価対象外。無限時間や酸素不要とは表示しません。</p>:<><div className={'overall '+(r.remainingMargin!<0?'danger':'')} role="status"><strong>{r.remainingMargin!<0?`酸素の参考計算では ${displayAmount(-r.remainingMargin!)} 分不足しています`:r.remainingMargin===0?'酸素の参考計算では予定時間と同じです（余裕0分）':`酸素の参考計算では ${displayAvailable(r.remainingMargin)} 分の余裕があります`}</strong><p>未検証の式・入力条件による時間差です。実際の持続時間や搬送可否は保証しません。</p></div><div className="result-metrics"><div><small>酸素の参考残時間</small><strong>{displayTime(r.safeDurationMinutes)}</strong></div><div><small>搬送予定（追加時間込み）</small><strong>{displayTime(r.input.transportMinutes)}</strong></div></div></>}<details><summary>Total Leakを変えた場合の式の比較</summary>{r.simulation.map(s=><p key={s.increment}>Total Leak +{s.increment} L/min：{displayTime(s.safeDurationMinutes)}</p>)}<p>添付コードの比較条件（+0/+10/+20）。実際のリーク変動予測や推奨値ではありません。</p></details></>}<details><summary>計算の内訳・注意点</summary><p>出典：利用者添付 V60--main.zip、oxygenCalculation.ts。メーカー検証済み資料ではありません。</p><p>ガス量 = ボンベ容量 × max（残圧−安全残圧, 0）÷満充填圧。</p><p>式上の消費量 =（MinVent＋Total Leak＋補正流量）×（FiO₂/100−0.21）÷0.79。係数適用時間 = ガス量÷式上の消費量×安全係数（%÷100）。</p><p>丸め・表示はおたすけくんの規則を適用：時間/量を切捨て、不足を切上げ。元コードの緑・黄・赤の搬送判定は採用しません。交換・補充は未対応。モデル版 imported-v60-experimental-1.0。</p></details></section>;
}
