import {useId} from 'react';
import type {Plan} from '../core/types';
import {displayAmount,displayAvailable,displayTime} from '../core/validation';
import {estimateReference,REFERENCE_VERSION} from '../modules/transport/reference';
export function ReferenceInputs({plan,change}:{plan:Plan;change:(p:Plan)=>void}){
 const prefix=useId();
 const field=(key:string,label:string,unit:string,hint:string)=><div className="field" key={key}><label htmlFor={prefix+key}>{label}</label><div className="input-unit"><input id={prefix+key} inputMode="decimal" value={plan.fields[key]??''} onChange={e=>change({...plan,fields:{...plan.fields,[key]:e.target.value}})}/><span>{unit}</span></div><small>{hint}</small></div>;
 return <section className="reference-input"><h3>酸素残時間の参考計算</h3><p>消費流量を仮定して比較します。実機の消費量を推定する式ではありません。</p><div className="grid">{field('refVolume','ボンベの容器内容積','L','容器の刻印・仕様を確認。「500 L級」の公称容量は入力しません。')}{field('refReserve','使用せず残す圧力（仮定）','MPa','独自の推奨値はありません。0なら留保なしの計算です。')}{field('refRate0','仮定する酸素消費流量','L/min','値の妥当性は未確認です。MinVent・リークから自動換算しません。')}</div><details><summary>別の消費流量でも比較する（任意）</summary><div className="grid">{field('refRate1','比較用の消費流量 2','L/min','空欄ならこのシナリオは計算しません。')}{field('refRate2','比較用の消費流量 3','L/min','空欄ならこのシナリオは計算しません。')}</div></details><button onClick={()=>change({...plan,segments:plan.segments.map(s=>({...s,times:{...s.times,exam:'0',wait:'0',connect:'0',delay:'0'}}))})}>検査・待機・接続・追加遅延はない（0分を入力）</button><small>時間がある場合は「検査・待機がある場合」を開いて入力してください。</small></section>;
}
export function ReferenceResults({plan}:{plan:Plan}){
 const r=estimateReference({pressure:plan.fields.cylinderPressure??'',volume:plan.fields.refVolume??'',reserve:plan.fields.refReserve??'',rates:[0,1,2].map(i=>plan.fields['refRate'+i]??''),times:plan.segments.flatMap(s=>Object.values(s.times))});
 return <section className="reference-result" aria-label="酸素の参考残時間"><h3>酸素の参考残時間 · 仮定による計算</h3><p className="notice">この流量以下で消費すると確認できていません。表示時間まで持つこと、搬送可能であることを保証しません。電源・空気は供給を確保する想定です。</p>{Object.keys(r.errors).length>0?<div role="alert"><p>参考計算に必要な入力を確認してください。</p>{Object.entries(r.errors).map(([key,value])=><p className="error" key={key}>{key.startsWith('time')?'時間：移動・検査・待機・接続・遅延の全項目（不要なら0）':({pressure:'現在残圧',volume:'容器内容積',reserve:'留保圧',rate0:'仮定流量',rate1:'比較流量2',rate2:'比較流量3'} as Record<string,string>)[key]??'計算'}：{value}</p>)}</div>:<><p>概算酸素量 {displayAvailable(r.available)} L ／ 必要時間 {displayTime(r.minutes)}（追加遅延込み）</p>{r.scenarios.map((s,i)=><div className={'resource '+(s.difference<0?'danger':'hold')} key={i}><strong>仮定流量 {s.flow} L/min</strong><h3>参考残時間 {displayTime(s.duration)}</h3><p>{s.difference<0?`予定に対して ${displayAmount(-s.difference)} 分不足／酸素 ${displayAmount(s.shortage)} L不足`:`この仮定での時間差 +${displayAvailable(s.difference)} 分`}</p><small>酸素だけの仮定計算。空気・電源と、実際の消費変動は別確認。</small></div>)}</> }<details><summary>参考計算の式・仮定・版</summary><p>概算酸素量 = 容器内容積 × max（現在残圧 − 留保圧, 0）÷ 0.1013 MPa。ゲージ圧を用いた一般的な理想気体概算です。温度・実在気体・供給系の制限、ボンベの個別換算表は反映していません。</p><p>参考残時間 = 概算酸素量 ÷ 仮定した酸素消費流量。流量が一定の単独ボンベを想定。補充・交換・同時接続は扱いません。留保圧は機器入口の最低供給圧とは異なります。</p><p>必要時間は入力した移動・検査・待機・接続・遅延の合計。FiO₂・MinVent・Total Leakはこの計算に使いません。機器設定の推奨やリーク増加の予測はしません。</p><p>時間・酸素量は0.1単位切捨て、不足は0.1単位切上げ。時間差0は余裕なし。版 {REFERENCE_VERSION}。V60成人・院内の参考画面のみ。</p></details></section>;
}
