import {useState,useRef} from 'react';
import type {Plan,Evaluation,Resource} from './core/types';
import {displayAmount,displayAvailable,displayTime,fieldError,invalidate} from './core/validation';
import {profiles,getProfile} from './profiles';
import {emptyPlan,demoExample} from './modules/transport/demoModel';
import {Guide} from './components/Guide';
import {evaluate} from './modules/transport/engine';
const VERSION='0.5.0-prototype';
const labels:Record<Resource,string>={oxygen:'酸素',air:'圧縮空気',power:'電源'};
const checklist=['① 設定：機器・回路・付属品と、FiO₂・換気／リーク・残圧・電源の最新値を実機と照合した','② ガス：酸素・必要な空気、ボンベ・減圧弁・接続・供給能力を確認した','③ 電源：本体・加温加湿器・周辺機器の電源と、切替後の作動を確認した','④ 到着・交換：到着先の接続環境、交換用資源・担当・交換手順を確認した','⑤ 最終確認：緊急時の代替手段を準備し、別の担当者と照合した'];
const stamp=(s:string)=>s?new Date(s).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo',hour12:false})+' JST':'未取得';
function Check({label,value,onChange,disabled=false}:{label:string;value:boolean;onChange:(v:boolean)=>void;disabled?:boolean}){return <label className="check"><input type="checkbox" checked={value} disabled={disabled} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>;}
function NumberInput({label,unit,value,onChange,hint,error,at}:{label:string;unit:string;value:string;onChange:(v:string)=>void;hint?:string;error?:string;at?:string}){const id=useRef('n-'+Math.random().toString(36).slice(2));return <div className="field"><label htmlFor={id.current}>{label}</label><div className="input-unit"><input id={id.current} type="text" inputMode="decimal" value={value} onChange={e=>onChange(e.target.value)} aria-invalid={!!error} aria-describedby={id.current+'-help'}/><span>{unit}</span></div><small id={id.current+'-help'}>{hint}{at&&<>／取得時刻：{stamp(at)}</>}{error&&<strong className="error">{error}</strong>}</small></div>;}
export default function App(){
 const [plan,setPlan]=useState<Plan>(()=>emptyPlan('clinical'));const [result,setResult]=useState<Evaluation|null>(null);
 const [checks,setChecks]=useState(checklist.map(()=>false));const [changed,setChanged]=useState(false);const [inputAt,setInputAt]=useState('');
 const profile=getProfile(plan.profileId)!;
 function change(next:Plan,key?:string){const now=new Date().toISOString();setPlan({...next,readings:{...next.readings,...(key?{[key]:now}:{})}});setInputAt(now);const s=invalidate({result,checks});setResult(s.result);setChecks(s.checks);setChanged(true);}
 function begin(mode:Plan['mode']){setPlan(emptyPlan(mode));setResult(null);setChecks(checklist.map(()=>false));setChanged(false);setInputAt('');}
 function example(){change(demoExample());}
 function calculate(){setResult(evaluate(plan));setChanged(false);setChecks(checklist.map(()=>false));}
 const allChecks=checks.every(Boolean);const shortage=result?.resources.filter(r=>(r.shortage??0)>0)??[];
 return <main className="simple-app">
 <header><div className="brandmark" aria-hidden="true">＋</div><div><small>臨床工学科</small><h1>業務お助け君</h1><p>呼吸療法機器の搬送準備</p></div></header>
 <div className="mode-row"><button aria-pressed={plan.mode==='clinical'} onClick={()=>begin('clinical')}>実機の準備確認</button><button aria-pressed={plan.mode==='demo'} onClick={()=>begin('demo')}>デモを試す</button></div>
 <p className="notice">{profile.demo?'デモ・臨床使用不可 — 架空装置の操作例です。':'参考・準備確認用。患者の搬送可否を自動判定しません。'}</p>
 <Guide message={changed?'入力が変わったよ。もう一度「結果を見る」を押してね。':!result?'実機の表示を見ながら、上から順に入力しよう。分からない値は先輩MEに確認してね。':shortage.length?'不足している資源があるよ。先輩MEと一緒に計画を見直そう。':result.overall==='判定保留'?'まだ未確認の項目があるよ。結果の「未確認事項」を開いて確認しよう。':allChecks?'チェックがそろったよ。実機の設定が変わっていないか、最後にもう一度確認しよう。':'結果を確認したら、出発前の5項目を実機と照合しよう。'}/><section className="card"><h2>1. 入力する</h2>
 {profile.demo?<div className="row"><p>架空装置 DEMO-01</p><button onClick={example}>デモ例を読み込む</button></div>:<label className="field">使用する機器<select value={plan.profileId} onChange={e=>change({...emptyPlan('clinical'),profileId:e.target.value})}>{profiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}
 <div className="grid">
 <NumberInput label="① 酸素ボンベ残圧" unit="MPa" value={profile.demo?plan.cylinders[0]?.pressure??'':plan.fields.cylinderPressure??''} onChange={v=>change(profile.demo?{...plan,cylinders:plan.cylinders.map((c,i)=>i===0?{...c,pressure:v}:c)}:{...plan,fields:{...plan.fields,cylinderPressure:v}},'cylinderPressure')} hint="ボンベの圧力計を読む" error={result?.errors['field.cylinderPressure']}/>
 {!profile.demo&&profile.fields.filter(f=>['fio2','vent','leak','addition'].includes(f.id)).map((f,i)=><NumberInput key={f.id} label={`${i+2}. ${f.id==='vent'?'分時換気量（MinVent）':f.id==='leak'?'総リーク量（Total Leak）':f.label}`} unit={f.unit} value={plan.fields[f.id]??''} onChange={v=>change({...plan,fields:{...plan.fields,[f.id]:v}},f.id)} hint={f.location} error={plan.fields[f.id]!==undefined?fieldError(plan.fields[f.id],f)??undefined:undefined}/>)}
 <NumberInput label="⑤ 搬送予定時間" unit="分" value={plan.segments[0]?.times.move??''} onChange={v=>change({...plan,segments:plan.segments.map((s,i)=>i===0?{...s,times:{...s.times,move:v}}:s)},'transport')} hint="移動に使う時間。往復なら往復分を入力" error={result?.errors['segment.s1.move']}/>
 </div><details><summary>検査・待機がある場合／電源・その他の入力</summary><label className="field">搬送区分<select value={plan.environment} onChange={e=>change({...plan,environment:e.target.value as Plan['environment']})}><option value="internal">院内搬送</option><option value="external">他院搬送（確認のみ）</option></select></label>
 {plan.segments.map((s,i)=><div key={s.id}><h3>{plan.segments.length>1?s.name:'移動以外に使う時間'}</h3><div className="grid">{(['exam','wait','connect','delay'] as const).map((k)=><NumberInput key={k} label={`${i+1}. ${{exam:'検査',wait:'待機',connect:'接続まで',delay:'追加の遅延'}[k]}`} unit="分" value={s.times[k]} onChange={v=>change({...plan,segments:plan.segments.map((x,j)=>i===j?{...x,times:{...x.times,[k]:v}}:x)})} hint="該当しない場合は0"/>)}{i>0&&<NumberInput label="復路の移動時間" unit="分" value={s.times.move} onChange={v=>change({...plan,segments:plan.segments.map((x,j)=>i===j?{...x,times:{...x.times,move:v}}:x)})}/>}</div></div>)}
 {profile.demo?<NumberInput label="架空電源の使用可能時間" unit="分" value={plan.powerMinutes} onChange={v=>change({...plan,powerMinutes:v})} hint="デモ専用。電池残量％からは換算しません"/>:<label className="field">電源の状態<input value={plan.fields.power??''} onChange={e=>change({...plan,fields:{...plan.fields,power:e.target.value}})} placeholder="本体・加湿器・周辺機器を確認"/></label>}
 {!profile.demo&&profile.fields.filter(f=>!['fio2','vent','leak','addition'].includes(f.id)).map(f=><NumberInput key={f.id} label={f.label} unit={f.unit} value={plan.fields[f.id]??''} onChange={v=>change({...plan,fields:{...plan.fields,[f.id]:v}},f.id)} hint={f.location}/>)}
 </details><div className="row"><small>入力は保存・外部送信しません。</small><button onClick={()=>begin(plan.mode)}>入力をクリア</button></div></section>
 <button className="primary calculate" onClick={calculate}>{profile.demo?'デモ結果を見る':'資源の確認結果を見る'} →</button>
 {changed&&<p className="notice" role="alert">入力が変わりました。結果と出発前チェックを更新してください。</p>}
 <section className="card" aria-label="資源の結果" aria-live="polite"><h2>2. 結果を確認する</h2>{!result?<p>入力後に「結果を見る」を押してください。</p>:<><div className="overall"><strong>総合：{result.overall}</strong><p>{profile.demo?'入力条件でのデモ評価です。':'消費量・電源時間が未確認のため、使用可能時間は算出していません。'}</p></div>{shortage.length>0&&<div className="shortage" role="alert"><strong>⚠ 資源不足</strong>{shortage.map(r=><p key={r.resource}>{labels[r.resource]}：{displayAmount(r.shortage)} {r.unit}不足</p>)}</div>}<p><strong>次の行動：</strong>{shortage.length?'資源または搬送計画を見直す':result.overall==='判定保留'?'未確認項目を先輩MEと確認する':'出発前の5項目を確認する'}</p><div className="resources cards">{result.resources.map(r=><div className={'resource '+(r.status==='資源不足'?'danger':r.status==='判定保留'?'hold':'')} key={r.resource}><h3>{labels[r.resource]}</h3><strong>{r.status}</strong>{profile.demo?<p>使用可能 {displayAvailable(r.available)} {r.unit}<br/>必要 {displayAmount(r.needed)} {r.unit}</p>:<p>{r.resource==='oxygen'?'実際の酸素消費量が未確認':r.resource==='air'?'機器・構成ごとの必要性を確認':'バッテリーと接続機器を確認'}</p>}</div>)}</div><details><summary>計算の内訳・未確認事項</summary><p>予定 {displayTime(result.planned)}／遅延込み {displayTime(result.evaluated)}</p>{result.reasons.map((r,i)=><p key={i}>{r}</p>)}{Object.entries(result.errors).map(([k,v])=><p className="error" key={k}>{v}</p>)}{result.resources.map(r=><div key={r.resource}>{r.ledger.map((l,i)=><p key={i}>{l.segment}：開始 {displayAvailable(l.start)} → 使用 {displayAmount(l.used)} → 残り {displayAvailable(l.end)} {r.unit}</p>)}</div>)}<p>入力 {stamp(inputAt)}／計算 {stamp(result.calculatedAt)}<br/>モデル {result.modelId??'未登録'}／プロファイル {result.profileVersion}</p></details></>}</section>
 <section className="card"><h2>3. 出発前に確認する</h2><Guide compact message="一人で迷ったら、先輩MEと一緒に確認しよう。チェックは実機を見てから付けてね。"/><p>実機を見ながら確認。分からなければ先輩MEへ。</p><small>確認済み {checks.filter(Boolean).length} / 5</small>{checklist.map((l,i)=><Check key={l} label={l} value={checks[i]} disabled={!result} onChange={v=>setChecks(checks.map((b,j)=>i===j?v:b))}/>)}{allChecks&&<p className="notice">準備チェック完了。患者の搬送可否を示すものではありません。</p>}</section>
 <details className="card"><summary>根拠・利用上の注意</summary><p>実機側の変更は自動検知できません。出発直前に再照合してください。</p><p>添付版のMinVent＋Total Leak＋補正流量の式は、実機の酸素消費式として確認できていないため使用していません。実機の臨床数値は未表示です。デモは架空の直接流量とボンベ条件のみを用います。</p><p>8機種は調査中。ボンベ換算・係数・電源モデル・院外適用は未登録です。</p><p>問い合わせ先・代替手順：未登録</p><p>MEサポくんは本アプリ用のオリジナル試作キャラクターです。</p><a href="https://mghp.ome.tokyo.jp/diagnosis/clinicalengineering" target="_blank" rel="noreferrer">参考：市立青梅総合医療センター 臨床工学科</a><a href="./downloads/clinical-engineering-helper-source.zip" download>ソースをダウンロード</a></details><footer>開発用試作 {VERSION} · 患者情報不要 · 再読込みで入力を消去</footer>
 </main>;
}
